### ISSUE TITLE
release new version please

### ISSUE THREAD

**Issue by TayouVR** [Dreadrith/VRCSDKPlus#1]
I like to get my packages from OpenUPM. the latest tag doesn't have the meta files. 
Could you please tag a release for the last commit?

**Comment by Dreadrith** [comment]
I'm not sure I understand what you're talking about?

**Comment by TayouVR** [comment]
You did a new release and have since resolved the isssue.

What this was talking about are packages managed through a UPM registry. They are immutable, which means unity cannot generate meta files for them. v1.3.5 did not have all the meta files included, which caused unity to chope up and not import the package at all (because package.json didn't have a meta file)

**Comment by Dreadrith** [comment]
Ah gotcha. Well glad it got solved lol.
